strengejacke/ggeffects

R/get_predictions_stan.R, tests/testthat/test-brms-categ-cum.R
Otherwise the probabilities will get assigned to the wrong category
=> Make sure response values are sorted when categorical response is numeric

.github/workflows/pkgdown.yml, _pkgdown.yml, pkgdown/extra.scss
=> Harmonize website look with `{easystats}`

DESCRIPTION, NEWS.md, R/hypothesis_test.R, man/hypothesis_test.Rd
=> Add equivalence test to `hypothesis_test()`

DESCRIPTION, NEWS.md, R/ggemmeans.R, R/ggpredict.R, R/pool_predictions.R, R/post_processing_labels.R, R/utils_ggpredict.R, R/utils_set_attr.R, tests/testthat/test-as_data_frame.R, tests/testthat/test-pool_predictions.R
=> pool_predictions for log-linear models: confidence intervals are not back-transformed

DESCRIPTION, NEWS.md, R/plot.R
=> ggpredict plot with residuals misplaces axis ticks for a releveled factor

DESCRIPTION, NEWS.md, R/plot.R, R/utils_get_representative_values.R, tests/testthat/test-scoping.R
=> Terms substitution fails when run inside a function

.lintr, DESCRIPTION, NEWS.md, R/plot.R, R/predictions.R, R/print.R, R/residualize_over_grid.R, R/simulate_predictions.R, R/standard_error_predictions.R, R/themes.R, R/utils.R, R/utils_colors.R, R/utils_get_data_grid.R, R/utils_get_representative_values.R, R/utils_reshape.R, R/utils_select.R, R/utils_typical_value.R, R/vcov.R, man/plot.Rd, tests/testthat/test-offset_zeroinfl.R, tests/testthat/test-resid_over_grid.R
=> Change color in ggeffects plot (one level)

DESCRIPTION, NEWS.md, R/hypothesis_test.R, tests/testthat/test-print_hypothesis_test.R
=> hypothesis_test not recognizing rows above 10 for contrasts

DESCRIPTION, NEWS.md, R/vcov.R, tests/testthat/test-ci_backticks-names.R, vignettes/technical_differencepredictemmeans.Rmd
=> Differences between ggpredict and ggemmeans (mixed-effects models and CI calculation)

DESCRIPTION, NEWS.md, R/residualize_over_grid.R
=> Partial residuals not available.

R/ggemmeans.R, R/ggpredict.R, R/vcov.R, _pkgdown.yml, man/ggpredict.Rd, man/vcov.Rd, tests/testthat/test-vcov.R, vignettes/content.Rmd
=> Some suggestions for `ggpredict()`

DESCRIPTION, NEWS.md, R/getter.R, R/post_processing_labels.R, R/utils_handle_labels.R, tests/testthat/_snaps/print_hypothesis_test.md, tests/testthat/test-plot.R
=> x-axis labels wrong (?)

DESCRIPTION, NEWS.md, R/plot.R, R/utils.R, tests/testthat/test-brms-trial.R, tests/testthat/test-glmmTMB.R, tests/testthat/test-interval_re.R, tests/testthat/test-poly-zeroinf.R, tests/testthat/test-print_hypothesis_test-ordinal.R, tests/testthat/test-resid_over_grid.R, tests/testthat/test-scoping.R, vignettes/practical_intersectionality.Rmd
=> "Could not find model object to extract residuals." when model is not in global envir

DESCRIPTION, NEWS.md, R/ggpredict.R, R/new_data.R, R/simulate_predictions.R, R/standard_error_predictions.R, R/utils.R, R/vcov.R, tests/testthat/test-add_data_missings.R, tests/testthat/test-get_titles.R
=> "Raw data not available." with weights and missing data

DESCRIPTION, NEWS.md, R/plot.R, man/plot.Rd
=> X value seemingly transformed for partial residuals plot

DESCRIPTION, NEWS.md, R/collapse_re_data.R, R/get_predictions_clmm.R, R/plot.R, R/residualize_over_grid.R, R/utils.R, R/utils_colors.R, R/utils_get_data_grid.R, R/utils_typical_value.R, R/vcov.R, man/plot.Rd, tests/testthat/test-add_data_missings.R
=> Data labels for points using plot()

DESCRIPTION, NEWS.md, R/ggeffect.R, R/ggemmeans.R, R/ggpredict.R, R/utils_get_data_grid.R, tests/testthat/test-backtransform_response.R, tests/testthat/test-betareg.R, tests/testthat/test-brms-ppd.R, tests/testthat/test-brms-trial.R, tests/testthat/test-clm.R, tests/testthat/test-rq.R, tests/testthat/test-tibble.R
=> ggpredict fails with one term when data used for modelling was a tibble

DESCRIPTION, NEWS.md, R/plot.R
=> Adding ggplot2 functionality to ggeffects plot() fails when not setting "terms"

DESCRIPTION, NEWS.md, R/ggeffect.R, tests/testthat/test-nestedLogit.R
=> Wrong effects computed for nestedLogit models

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md, R/hypothesis_test.R, R/johnson_neyman.R, man/hypothesis_test.Rd, man/johnson_neyman.Rd, tests/testthat/test-johnson_neyman.R, tests/testthat/test-parsnip.R
=> Johnson-Neyman FDR Correction

DESCRIPTION, NEWS.md, R/emmeans_prediction_data.R, R/get_predictions_rqs.R, R/ggemmeans.R, R/hypothesis_test.R, R/predictions.R, R/utils.R, R/utils_get_data_grid.R, R/utils_handle_labels.R, R/utils_model_function.R, R/utils_set_attr.R, README.rmd, tests/testthat/test-rq.R
=> New incompatibilities with emmeans for quantile regression

DESCRIPTION, NEWS.md, R/format.R, R/get_predictions_stan.R, R/predictions.R, tests/testthat/_snaps/print.md, tests/testthat/_snaps/print_hypothesis_test.md, tests/testthat/test-prediction_interval.R, tests/testthat/test-print.R, tests/testthat/test-print_hypothesis_test.R
=> Difference between insight::get_predicted and ggeffects::ggpredict when calculating PI

DESCRIPTION, NEWS.md, R/utils_get_data_grid.R, tests/testthat/test-fixest.R
=> missing errors when using fixest models

DESCRIPTION, NEWS.md, R/emmeans_prediction_data.R, R/ggemmeans.R, R/ggemmeans_zi_predictions.R, R/ggpredict.R, R/predict_response.R, R/predict_zero_inflation.R, R/utils_get_data_grid.R, man/ggpredict.Rd, man/predict_response.Rd, tests/testthat/test-brms-categ-cum.R, tests/testthat/test-glmmTMB.R, tests/testthat/test-rstanarm.R, tests/testthat/test-zi_prob.R, vignettes/introduction_randomeffects.Rmd
=> zi_prob-type predictions with new predict_response function

DESCRIPTION, NEWS.md, R/test_predictions.R, R/test_predictions_emmeans.R, man/test_predictions.Rd, tests/testthat/test-test_predictions_emmeans.R
``` r
library(ggeffects)
library(emmeans)
data(efc)
efc$c172code <- as.factor(efc$c172code)
efc$c161sex <- as.factor(efc$c161sex)
efc$e15relat <- as.factor(efc$e15relat)
efc$e42dep <- as.factor(efc$e42dep)
levels(efc$c161sex) <- c("male", "female")
m <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
test_predictions(m, "c172code", engine = "emmeans")
#> # Pairwise comparisons
#> 
#> c172code | Contrast |      95% CI |     p
#> -----------------------------------------
#> 1-2      |    -2.88 | -7.05, 1.28 | 0.175
#> 1-3      |    -1.22 | -6.51, 4.08 | 0.652
#> 2-3      |     1.67 | -2.76, 6.10 | 0.460
test_predictions(m, "neg_c_7", engine = "emmeans")
#> # Pairwise comparisons
#> 
#> neg_c_7 | Slope |       95% CI |      p
#> ---------------------------------------
#> …
```
=> test_predictions using emmeans

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md, R/ggeffect.R, R/plot.R, R/test_predictions_ggeffects.R, R/utils_set_attr.R, tests/testthat/_snaps/plot-ordinal-latent.md, tests/testthat/_snaps/plot-ordinal-latent/clm-latent-false.svg, tests/testthat/_snaps/plot-ordinal-latent/clm-latent-true.svg, tests/testthat/_snaps/plot-ordinal-latent/polr-latent-false.svg, tests/testthat/_snaps/plot-ordinal-latent/polr-latent-true.svg, tests/testthat/test-plot-ordinal-latent.R, tests/vdiffr.Rout.fail
=> Plotting ordinal logistic predicted effects on latent scale of ordinal outcome?

DESCRIPTION, NEWS.md, R/get_predictions_stan.R, R/predict_response.R, man/predict_response.Rd, tests/testthat/test-rstanarm.R
=> ggpredict() returns 90% CI when ppd = TRUE for rstanarm models, but labeled as 95%

DESCRIPTION, R/test_predictions.R, R/test_predictions_ggeffects.R, tests/testthat/test-gamm4.R, tests/testthat/test-test_predictions_ggeffects.R
=> test_predictions not working with gamm4 model output

R/predict_response.R, man/predict_response.Rd, vignettes/introduction_randomeffects.Rmd
=> reference issue in "Introduction_randomeffects.Rmd"

DESCRIPTION, NEWS.md, R/ggaverage.R, R/ggeffect.R, R/ggemmeans.R, R/ggpredict.R, R/utils_ggpredict.R, tests/testthat/_snaps/backtransform_response/show-data-back-transformed-false.svg, tests/testthat/_snaps/backtransform_response/show-data-back-transformed-true.svg, tests/testthat/test-backtransform_response.R
=> plot add data=TRUE not making sense

R/predict_response.R, man/predict_response.Rd
=> Is the full average or conditional average after model.avg used in ggpredict?

DESCRIPTION, NEWS.md, R/collapse_re_data.R, tests/testthat/_snaps/plot/collapse-random-effects-works-again.svg, tests/testthat/test-plot.R
=> "Collapse_group" produces many data points

DESCRIPTION, NEWS.md, R/emmeans_prediction_data.R, R/get_predictions_glmmTMB.R, R/get_predictions_merMod.R, R/ggemmeans_add_confint.R, R/predictions.R, tests/testthat/test-glm.R, tests/testthat/test-glmmTMB.R
```r
library(ggeffects)
library(datawizard)
library(lme4)
data(sleepstudy)
d <- sleepstudy |>
data_filter(Days %in% 1:4) |> 
data_modify(Days = as.factor(Days))
m <- glmer(Reaction ~ Days + (1 | Subject), data = d, family = Gamma())
predict_response(m, "Days")
```
TODO:
=> Fix issue with CI for models with inverse-link

DESCRIPTION, NEWS.md, R/get_predictions_multinom.R, R/predictions.R, R/standard_error_predictions.R, R/utils_model_function.R, R/vcov.R, README.rmd, tests/testthat/test-avg_predictions.R
=> Breaking change in `marginaleffects` 0.22.0

R/test_predictions.R, R/test_predictions_ggeffects.R, man/test_predictions.Rd
=> `test_prediction()` should consider `condition` argument

DESCRIPTION, NEWS.md, R/get_predictions_coxph.R, R/get_predictions_gamlss.R, R/get_predictions_generic2.R, R/get_predictions_zeroinfl.R, R/predictions.R, R/standard_error_predictions.R, R/vcov.R, tests/testthat/test-condition.R, tests/testthat/test-gamlss.R
=> predict_response adjusting for additional continuous variable drops CI calculations

DESCRIPTION, R/standard_error_predictions.R, R/utils_get_data_grid.R, R/vcov.R, tests/testthat/test-backtransform_response.R, tests/testthat/test-brms-ppd.R, tests/testthat/test-brms-trial.R, tests/testthat/test-gamlss.R, tests/testthat/test-glmer.R
=> Memory issue with ggpredict/predict_response of fixest object

DESCRIPTION, R/get_predictions_lme.R, tests/testthat/test-plm.R
=> Add support for "plm"

DESCRIPTION, NEWS.md, R/ggaverage.R, tests/testthat/test-ggaverage.R
=> Using an offset with method='empirical'

DESCRIPTION, NEWS.md, R/get_predictions_averaging.R, R/get_predictions_betareg.R, tests/testthat/test-averaging.R
=> Unable to produce confidence intervals with ggpredict using model.avg Beta regression
